events {}

http {
    upstream backend-server {
        server server:3001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend-server;
        }
    }
}