services:
  proxy:
    build: ./proxy
    image: funko-proxy
    ports:
      - "8080:80"
    depends_on:
      - back
    networks:
      - funko-data
      
  back:
    build: ./back
    image: funko-back
    depends_on:
      db:
        condition: service_healthy
    networks:
      - funko-db
      - funko-data

  db:
    image: postgres:12-alpine
    env_file:
      - db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 1
      timeout: 10s
    networks:
      - funko-db

networks:
  funko-data:
    driver: bridge

  funko-db:
    driver: bridge